Azureml train pipeline (#195)
* initial add of azure ml pipeline

* update references and dependencies

* fix integration tests

* remove incomplete tests

* add azureml requirements.txt for dutchf3 local patch and update pipeline config

* add empty __init__.py to cv_lib dutchf3

* Get train,py to run in pipeline

* allow output dir in train.py

* Clean up README and __init__

* only pass output if available and use input dir for output in train.py

* update comment in train.py

* updating azureml_requirements to only pull from /master

* removing windows guidance in azureml_pipelines/README.md

* adding .env.example

* adding azureml config example

* updating documentation in azureml_pipelines README.md

* updating main README.md to refer to AML guidance documentation

* updating AML README.md to include additional guidance to cancel runs

* adding documentation on AzureML pipelines in the AML README.me

* adding files needed section for AML training run

* including hyperlink in format poiniting to additional detail on Azure Machine Learning pipeslines in AML README.md

* removing the mention of VSCode in the AML README.md

* fixing typo

* modifying config to pipeline configuration in README.md

* fixing typo in README.md

* adding documentation on how to create a blob container and copy data onto it

* adding documentation on blob storage guidance

* adding guidance on how to get the subscription id

* adding guidance to activate environment and then run the kick off train pipeline from ROOT

* adding ability to pass in experiement name and different pipeline configuration to kickoff_train_pipeline.py

* adding Microsoft Corporation Copyright to kickoff_train_pipeline.py

* fixing format in README.md

* adding trouble shooting section in README.md for connection to subscription

* updating troubleshooting title

* adding guidance on how to download the config.json from the Azure Portal in the README.md

* adding additional guidance and information on AzureML compute targets and naming conventions

* changing the configuation file example to only include the train step that is currently supported

* updating config to pipeline configuration when applicable

* adding link to Microsoft docs for additional information on pipeline steps

* updated AML test build definitions

* updated AML test build definitions

* adding job to aml_build.yml

* updating example config for testing

* modifying the test_train_pipeline.py to have appropriate number of pipeline steps and other required modifications

* updating AML_pipeline_tests in aml_build.yml to consume environment variables

* updating scriptType, sciptLocation, and inlineScript in aml_build.yml

* trivial commit to re-trigger broken build pipelines

* fix to aml yml build to use env vars for secrets and everything else

* another yml fix

* another yml fix

* reverting structure format of jobs for aml_build pipeline tests

* updating path to test_train_pipeline.py

* aml_pipeline_tests timed out, extending timeoutInMinutes from 10 to 40

* adding additional pytest

* adding az login

* updating variables in aml pipeline tests

Co-authored-by: Anna Zietlow <annamzietlow@gmail.com>
Co-authored-by: maxkazmsft <maxkaz@microsoft.com>

diff --git a/tests/cicd/aml_build.yml b/tests/cicd/aml_build.yml
--- a/tests/cicd/aml_build.yml
+++ b/tests/cicd/aml_build.yml
@@ -21,34 +21,89 @@ jobs:
   displayName: Setup
   pool:
     name: deepseismicagentpool
-
   steps:
-  - bash: |
-      # terminate as soon as any internal script fails
-      set -e
+    - bash: |
+        # terminate as soon as any internal script fails
+        set -e
 
-      echo "Running setup..."
-      pwd
-      ls
-      git branch
-      uname -ra
+        echo "Running setup..."
+        pwd
+        ls
+        git branch
+        uname -ra
 
-      # ENABLE ALL FOLLOWING CODE WHEN YOU'RE READY TO ADD AML BUILD - disabled right now
-      # ./scripts/env_reinstall.sh 
-      # use hardcoded root for now because not sure how env changes under ADO policy
-      # DATA_ROOT="/home/alfred/data_dynamic"
-      # ./tests/cicd/src/scripts/get_data_for_builds.sh ${DATA_ROOT}
-      # copy your model files like so - using dummy file to illustrate
-      # azcopy --quiet --source:https://$(storagename).blob.core.windows.net/models/model --source-key $(storagekey) --destination /home/alfred/models/your_model_name
+        # setup run environment
+        ./scripts/env_reinstall.sh 
 
-- job: AML_job_placeholder
+        # use hardcoded root for now because not sure how env changes under ADO policy
+        DATA_ROOT="/home/alfred/data_dynamic"
+        ./tests/cicd/src/scripts/get_data_for_builds.sh ${DATA_ROOT}
+
+        # upload pre-processed data to AML build WASB storage - overwrites by default and auto-creates container name
+        azcopy --quiet --recursive \
+          --source ${DATA_ROOT}/dutch_f3/data --destination https://${BLOB_ACCOUNT_NAME}.blob.core.windows.net/${BLOB_CONTAINER_NAME}/data \
+          --dest-key ${BLOB_ACCOUNT_KEY}
+      env:
+        BLOB_ACCOUNT_NAME: $(amlbuildstore)
+        BLOB_CONTAINER_NAME: "amlbuild"
+        BLOB_ACCOUNT_KEY: $(amlbuildstorekey)
+
+
+- job: AML_pipeline_tests
   dependsOn: setup
-  timeoutInMinutes: 5
-  displayName: AML job placeholder
+  timeoutInMinutes: 20
+  displayName: AML pipeline tests
   pool:
     name: deepseismicagentpool
   steps:
-  - bash: |
-      # UNCOMMENT THIS WHEN YOU HAVE UNCOMMENTED THE SETUP JOB
-      # source activate seismic-interpretation
-      echo "TADA!!"
+  - bash: |      
+      source activate seismic-interpretation
+      # TODO: add code which launches your pytest files ("pytest sometest" OR "python test.py")
+      # data is in  $(amlbuildstore).blob.core.windows.net/amlbuild/data (container amlbuild, virtual folder data)
+      # storage key is $(amlbuildstorekey)
+      az --version
+      az account show
+      az login --service-principal -u $SPIDENTITY -p $SPECRET --tenant $SPTENANT
+      az account set --subscription $SUB_ID
+      mkdir .azureml
+      cat <<EOF > .azureml/config.json
+      {
+        "subscription_id": "$SUB_ID",
+        "resource_group": "$RESOURCE_GROUP",
+        "workspace_name": "$WORKSPACE_NAME"
+      }
+      EOF
+      pytest interpretation/tests/test_train_pipeline.py || EXITCODE=123
+      exit $EXITCODE
+      pytest
+    env:
+      SUB_ID: $(subscription_id)
+      RESOURCE_GROUP: $(resource_group)
+      WORKSPACE_NAME: $(workspace_name)
+      BLOB_ACCOUNT_NAME: $(amlbuildstore)
+      BLOB_CONTAINER_NAME: "amlbuild"
+      BLOB_ACCOUNT_KEY: $(amlbuildstorekey)
+      BLOB_SUB_ID: $(subscription_id)
+      AML_COMPUTE_CLUSTER_NAME: "testcluster"
+      AML_COMPUTE_CLUSTER_MIN_NODES: "1"
+      AML_COMPUTE_CLUSTER_MAX_NODES: "8"
+      AML_COMPUTE_CLUSTER_SKU: "STANDARD_NC6"
+      SPIDENTITY: $(spidentity)
+      SPECRET: $(spsecret)
+      SPTENANT: $(sptenant)
+    displayName: 'integration tests'
+
+# - job: AML_short_pipeline_test
+#   dependsOn: setup
+#   timeoutInMinutes: 5
+#   displayName: AML short pipeline test
+#   pool:
+#     name: deepseismicagentpool
+#   steps:
+#   - bash: |      
+#       source activate seismic-interpretation
+#       # TODO: OPTIONAL! Add a job which launches entire training pipeline for 1 epoch of training (train model for single epoch)
+#       # if you don't want this then delete the entire job from this file
+#       python interpretation/deepseismic_interpretation/azureml_pipelines/dev/kickoff_train_pipeline.py --experiment=DEV-train-pipeline-name --orchestrator_config=orchestrator_config="interpretation/deepseismic_interpretation/azureml_pipelines/pipeline_config.json"
+
+
